### ISSUE TITLE
Excluded extensions

### ISSUE THREAD

**Issue by Alpvax** [dail8859/ElasticTabstops#11]
Could you allow for extensions to be ignored, using a pattern of ! .ext1 .ext2 etc. or something similar? I want to use the elastic tabstops for all files except a few

**Comment by dail8859** [comment]
@Alpvax 

I just committed a change adding this. It won't be avialable via the plugin manager any time soon so you can manually download it and copy over your ElasticTabstops DLL file. Download links are here:

- [32 bit](https://ci.appveyor.com/project/dail8859/elastictabstops/builds/19504865/job/dc0va4na9kyw39c0/artifacts)
- [64 bit](https://ci.appveyor.com/project/dail8859/elastictabstops/builds/19504865/job/e6h8ntauobhlgbo5/artifacts)

You can now specify extensions to ignore by prepending them with `!`. If none of the extension rules match then it does not apply Elastic Tabstops to the file. So in your case you can do something like:

    extensions !.ext1 !.ext2 *

That way it will ignore ext1 and ext2 but the `*` will allow it to match all other files.

If you run into any issues or questions feel free to let me know.

**Comment by Alpvax** [comment]
That's great, thanks
