### ISSUE TITLE
Evaluation: Add ElasticTabstops 1.3 and above to nppPluginList

### ISSUE THREAD

**Issue by MetaChuh** [dail8859/ElasticTabstops#13]
hi @dail8859 

as ElasticTabstops manual installation support has been requested a few times, and it is a much liked plugin, would there be a possibility to add your releases to nppPluginList, or is there anything that could speak against a large scale distribution via plugins admin ?

many thanks and best regards.

**Comment by dail8859** [comment]
In plugin list as well.
