### ISSUE TITLE
Plugin not working on V7.7 of notepad++ (64bit)

### ISSUE THREAD

**Issue by jschuppe** [dail8859/ElasticTabstops#14]
Since V7.7 of notepad++ (64bit) the plugin (V1.3) will not work properly. Tabstops are not "elastic" on the fly. I have to disable and then enable the plugin again, to get the tabstops will be "elastic".

**Comment by dail8859** [comment]
Need to investigate. Possibly related https://github.com/Predelnik/DSpellCheck/issues/179

**Comment by Loophole62ndFF** [comment]
I do hope it is easily fixed - I've come to rely heavily on Elastic Tabstops to enable me to work with tabbed files without having to resort to the lurking horror that is Excel.

**Comment by dail8859** [comment]
New release. https://github.com/dail8859/ElasticTabstops/releases/tag/v1.3.1
