### ISSUE TITLE
[Enhancement] Elastic CSV (Comma separated) files

### ISSUE THREAD

**Issue by mfinky** [dail8859/ElasticTabstops#15]
Not an Issue!  Only humble suggestions for enhancements.

Hello Justin (Dail8859), 
First of all THANK YOU for your outstanding contributions.  
I use and enjoy your elastic tabs and your surround selection.    Thanks!

I am using notepad++ v7.7.1 32 bit and Elastic Tabstops v1.3 32 bit.

Suggestion 'a': could we have a config option to use commas (",") or maybe "any" configurable char(s) as separator(s), (not only Tabs)?

With a configurable "separator char" i would be able to switch to commas and see a COMMA separated file as nicely as I get to see the Tab Separated files today.

Suggestion 'b':  Very often, i need to "normalize" a CSV file.  Meaning: surround each comma separated field and add opening and closing double quotes to it.  
(repeat for each row, whoe file or in-selection).
Use Case: I receive a csv file where only a few fields are surrounded by (").
Only those that _already_ contain a comma as part of the content text.
(I realize this is totally compliant with the CSV specs, but I deal with applications that are not smart enough to allow for it, and they require that all text fields in all rows be surrounded by double quotes).

So, I need to go over all rows adding the limiting double-quotes manually.
If a plugin could _"normalize"_ the csv file content ensuring all fields are enclosed in ("),  that would be really handy.

One more time: kudos and thank you for your contributions!

Marcelo Finkielsztein
mfinkielsztein@postmedia.com

**Comment by dail8859** [comment]
Glad you are finding this useful.

> could we have a config option to use commas (",") or maybe "any" configurable char(s) as separator(s), (not only Tabs)?

Unfortunately not. The only way to adjust the widths of the columns is by specifying where the tab stops at. 

> Very often, i need to "normalize" a CSV file.

This sounds a bit out of scope for this plugin. This is meant for source code alignment but happens to work for tab delimited files. Adding support specific for CSV or TSV files is not something I want to support.

> Use Case: I receive a csv file where only a few fields are surrounded by (").

This is probably doable with a regular expressions. Or something like LuaScript, PythonScript, etc.

**Comment by mfinky** [comment]
Hello again Sir.

Thank you for having considered my suggestion!    and your prompt response!

I believe I understand now why only Tabs!  clever!.
I believe I understand your points of view about the scope of the plugin.
I totally agree with your tips about regular expressions and scripting.

One more time:  THANKS!
:o) Marcelo Finkielsztein
