### ISSUE TITLE
1.3.1 does not work in the notepad++ 7.8

### ISSUE THREAD

**Issue by andry81** [dail8859/ElasticTabstops#17]
Platform: Windows 7 x64
Notepad++: 7.8 32-bit

Replaced DLL by 1.3.0 and works as expected.

**Comment by dail8859** [comment]
Could you provide your Notepad++ debug info (under the "?" menu) and also your ElasticTabstops settings file?

**Comment by andry81** [comment]
```
Notepad++ v7.8   (32-bit)
Build time : Oct  7 2019 - 00:58:16
Path : c:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS Name : Windows 7 Professional (64-bit) 
OS Build : 7601.0
Plugins : ElasticTabstops.dll JSMinNPP.dll mimeTools.dll NppConverter.dll NppExport.dll NPPJSONViewer.dll NppTextFX.dll PyNPP.dll PythonScript.dll 
```

**Comment by dail8859** [comment]
Could you post your settings as well?

Also, what does "not working" mean? Is it wrong? Does tabs not get aligned? Does it crash?

**Comment by andry81** [comment]
> Could you post your settings as well?

what settings?

> Also, what does "not working" mean? Is it wrong? Does tabs not get aligned? Does it crash?

tabs not get aligned

**Comment by dail8859** [comment]
Menu option `Plugins > Elastic Tabstops > Settings...`

Just copy paste the entire file here.

**Comment by andry81** [comment]
Strange, but after the plugin reinstall I couldn't repro it.

It sometimes happens that is doesn't work, but I still can not catch it.

**Comment by andry81** [comment]
```
; Configuration for ElasticTabstops.
; Saving this file will immediately apply the settings.

; Whether elastic tabstops are enabled or not: true or false
enabled true

; File extensions to apply elastic tabstops. For example...
;   "extensions *" will apply it to all files
;   "extensions .c .h .cpp .hpp" will apply it to only C/C++ files
;   "extensions !.txt !.py *" will apply it to all files except for text and Python files
extensions *

; Minimum padding in characters. Must be > 0
padding 1

; Convert leading tabs to spaces: true or false
convert_leading_tabs_to_spaces false
```

**Comment by dail8859** [comment]
If you do find a way to reproduce it let me know.

**Comment by radoslawch** [comment]
For me it didn't work too. It seems that Plugin Admin installed x86 version of DLL into my x64 Notepad++. After downloading manually 1.3.1 x64 version it's ok.

**Comment by dail8859** [comment]
Assuming this is related to #21 you can download the DLLs linked in that issue.
