### ISSUE TITLE
Not working :-(

### ISSUE THREAD

**Issue by matuskalas** [dail8859/ElasticTabstops#18]
Hey, I love the logo! ❤️ It's very pretty, and it suggest that this plugin does exactly what I need...

... _i.e._ enabling [tab stops](https://en.wikipedia.org/wiki/Tab_stop) (not tabs) to be moved around, making the all the tabs longer of shorter, without replacing them with spaces. Just like in a Word-like editor (which I'm definitely not going to use for reading TSV files).

Automatically or manually, any of these 2 options would work for me. I just need to read TSV files. (No I'm not going to use a spreadsheet app either). The post at https://community.notepad-plus-plus.org/topic/13795/aligning-columns promises exactly that, automatically.

![ElasticTabstops functionality](https://i.imgur.com/10G3tuF.png)

However, _ElasticTabstops_ do not seem to do ANYTHING for me, and I also haven't found any documentation ANYWHERE 😭

![ElasticTabstops not working](https://www.ii.uib.no/~matus/elasticTabstopsNotWorking.png)

Notepad++ v7.8.4. 32-bit

Please help!

**Comment by dail8859** [comment]
What version of ElasticTabstops are you using?

Also, in the first example can you run `View > Show Symbols > Show Whitespace and Tab` to ensure those are actually tab characters separating the columns?

In the 2nd example, since the two tab characters have a blank line between them then it will not have any affect.

**Comment by matuskalas** [comment]
Thanks for your quick response @dail8859, highly appreciated!

I use the version from Plugins Admin, _i.e._ the latest 1.3.1

The first screenshot was from https://community.notepad-plus-plus.org/topic/13795/aligning-columns

In my case, removing the empty line does not help :'(

![ElasticTabstops still not working](https://www.ii.uib.no/~matus/elasticTabstopsNotWorking2.png)

**Comment by dail8859** [comment]
There was an issue where the plugin would not work until  Notepad++ was restarted (see #21). 

Are you still having the issue?
