### ISSUE TITLE
Access violation reported when used in conjunction with Compare plugin

### ISSUE THREAD

**Issue by jimbobmcgee** [dail8859/ElasticTabstops#19]
Not sure if interoperation with another plugin concerns you, but I occasionally use the Compare plugin (from the Plugin Admin) to compare two files.

When ending the comparison, using their *Clear Active Compare* menu option, I get a number of dialog popups, all saying:

    Plugin Exception
    ----------------------
    An exception occurred due to plugin: ElasticTabstops.dll
    Exception reason: Access violation

*For background:* The Compare plugin appears to work by splitting the NPP window into two views (akin to right-clicking a tab and choosing *Move to new View*), so the two compared tabs are side-by-side, then shifting the content of both tabs so that matching lines are aligned next to each other.  When choosing to *Clear Active Compare*, that process is reversed, so the shifting of text is is undone and the tabs are moved back to the same view.

I get an Access Violation popup for every "unshift" that has to happen.  A block of text unshifts, the AV popup occurs, I click OK, and the next block un-shifts, etc.

It doesn't appear to be *fatal*, insofar as NPP will continue to run and, if I click through all the dialogs, both Compare and ETS continue to work.  It's just annoying to click through those dialogs, especially if there are a lot of text blocks that need to shift/unshift.

I'm running ETS v1.3 and Compare v2.0.0, currently against NPP v7.8.2 (32-bit).

**Comment by datacate** [comment]
I'm also getting this, with Notepad++ v7.8.4 32-bit on Windows 10, running  v1.3.1 of this plugin. I've removed all other plugins and I'm still getting the error. Appreciate any suggestions.

**Comment by dail8859** [comment]
Closed by 13780a86155b1198ad89c1628997b77a1a9e0a38

Until another release is made, you can download the appropriate DLL file below and just replace your existing ElasticTabstops.dll file

- 64 bit: https://ci.appveyor.com/project/dail8859/ElasticTabstops/branch/master/job/hoqyk43x86394471/artifacts
- 32 bit: https://ci.appveyor.com/project/dail8859/ElasticTabstops/branch/master/job/h8f872m2qljde35c/artifacts
