### ISSUE TITLE
Doesn't work until I change and save settings

### ISSUE THREAD

**Issue by paulelong** [dail8859/ElasticTabstops#21]
Great tool for notepad++.  This in combination with selected highlight makes finding numbers in tables easier.

My problem is that when I loaded my file, the data wasn't aligned.  The plugin showed as enabled by default.  It started working once I opened the settings and changed the padding from 1 to 15 and saved the settings.  Then all the tabs lined up, albeit with a large spacing.  Then I changed the padding back to 1 and it still lined up.  It seems to work fine now, but that first time it appeared it wasn't working until I did the steps above.  I had tried to restart notepad++, but that had no affect at the time.

My guess is there is some problem that occurs the very first time you install.

**Comment by dail8859** [comment]
What is your Notepad++ debug information?

What version of ElasticTabstops are you using?

Can you post an exact list of steps to reproduce the issue?

**Comment by Kered13** [comment]
I can second this bug. I'm using v7.8.2 64-bit with the plugin installed from the plugin admin.

I was able to reproduce by deleting the config file for ElasticTabstops, then opening Notepad++. Note that this file is not automatically created after installing the plugin until _after_ NP++ has been closed, or the file  has been manually edited. So after installing the plugin for the first time it did not work, which is what brought me here. Toggling the enabled setting while NP++ is running also has no effect when the config file has not yet been created.

**Comment by dail8859** [comment]
Until another release is made, you can download the appropriate DLL file below and just replace your existing ElasticTabstops.dll file

- 64 bit: https://ci.appveyor.com/project/dail8859/ElasticTabstops/branch/master/job/vrf1p7aag2haqx8o/artifacts
- 32 bit: https://ci.appveyor.com/project/dail8859/ElasticTabstops/branch/master/job/oe88i5qw4rn926q9/artifacts
