### ISSUE TITLE
Support for elastic/aligned tabs when printed?

### ISSUE THREAD

**Issue by jimbobmcgee** [dail8859/ElasticTabstops#22]
When printing a text file that has been written with ETS enabled, the resulting printout does not align the tabs to the elastic column positions.  

I have to remember to use the *Convert to spaces* function, then print, then CTRL+Z the conversion to spaces, and my memory for doing so seems to be failing me (especially the undoing after printing).

If you could add support for printing the tabs as they are displayed in the window (i.e. honoring the enabled/disabled state of ETS), that would certainly save me a headache!

I'm currently running ETS v1.3 against NPP v7.8.4 (32-bit), which I appreciate may be a bit behind the latest.

**Comment by dail8859** [comment]
I honestly don't think there is anything this plugin can do. When the the Scintilla editor is rendered for printing, it skips certain elements (caret, markers, extra margins) and I am assuming it just isn't set up to handle custom tab widths. Also I don't know of any way to intercept the "print" command and convert to spaces before being printed, then undo it after it is printed.

This would have to be something addressed by Scintilla, and even then I'm not sure that would be an easy case to handle. For instance this plugin doesn't align tabs for the entire document all at once, it normally just handles the visible area and some surrounding lines.

**Comment by jimbobmcgee** [comment]
I figured this would be the case.  I guess NPP does not expose a message for before/after printing yet, that you can reliably hook.

I thought about maybe hooking the `NPPM_MENUCOMMAND` message&mdash;where `lparam` is `IDM_FILE_PRINT` or `IDM_FILE_PRINTNOW`&mdash;to trigger a conversion of *tab-to-space*, but it probably doesn't give you an easy point to determine when printing has finished, or if the dialog is cancelled, to revert *space-to-tab*.

I guess the better approach is to ask NPP to expose specific print messages and/or an interface to the stream of data that is sent to the printer.  I assume you would need to spool twice -- once to determine the column widths and once to manipulate the print stream to space them.

Didn't expect any of this to be easy, though...

**Comment by dail8859** [comment]
As you said there just isn't enough interaction with Notepad++ in regards to printing...especially all the corner cases of canceling, finished, etc.

If it was as simple as: catch a new message (from either N++ or Scintilla) and then recalculate all the  column widths, then I would be fine adding this. Trying to modify anything other than just the Scintilla editor (such as the actual print stream) would be quite involved. 

For now I will close this issue. If somehow a clean interface is exposed by N++ or Scintilla then I will reevaluate it at that time, but I don't have high hopes for something like that getting implemented soon.

---

As some alternatives, I'm not sure if you can macro record converting to spaces and then printing...or if there is some way to script the behavior you want with one of the numerous scripting plugins.
