### ISSUE TITLE
Elastic Tabstops v1.3.1 (64 bit) breaks Notepad++ v8.3 (64-bit)

### ISSUE THREAD

**Issue by fjcbs** [dail8859/ElasticTabstops#28]
When this plugin is enabled, Notepad++ returns several "Access violation" errors.

**Comment by dail8859** [comment]
https://github.com/notepad-plus-plus/notepad-plus-plus/issues/11198

**Comment by marko090591** [comment]
rdipardo when we can expecta new version of addon?

**Comment by rdipardo** [comment]
@marko090591,

only @dail8859 knows that; the linked issue you saw is just an 
announcement to help users find a new version of their broken plugins.

Best option for now is to downgrade N++, just like @dail8859 suggested 
on the forum: 
https://community.notepad-plus-plus.org/topic/22527/elastictabstops-1-3-1-triggers-virus-alert-in-notepad-8-3-64-bit

**Comment by dail8859** [comment]
@marko090591

> when we can expecta new version of addon?

The short answer is...I don't know.
