### ISSUE TITLE
V1.3.1 does not work in the notepad++ 8.3.3

### ISSUE THREAD

**Issue by jschuppe** [dail8859/ElasticTabstops#29]
Since my update yesterdey to notepad++ V8.3.3 I can't see the ElasticsTabstop Plugin anymore

**Comment by dail8859** [comment]
Duplicate of #28

**Comment by peterfnet** [comment]
Ditto. Was unexpected. Not listed in plugin admin tool, file still exists in `C:\Program Files\Notepad++\plugins\ElasticTabstops\`, and it is not moved to the disabled plugin folder.

`"%APPDATA%\Notepad++\plugins\Config\ElasticTabstops.ini"` still exsists

**Comment by dail8859** [comment]
> Was unexpected. Not listed in plugin admin tool, file still exists in C:\Program Files\Notepad++\plugins\ElasticTabstops\, and it is not moved to the disabled plugin folder.

Notepad++ did a horrible job about telling the user _why_ their plugin is no longer there and why it can't be installed.
