### ISSUE TITLE
Exception and data corruption on using with compare plugin

### ISSUE THREAD

**Issue by qatanani** [dail8859/ElasticTabstops#5]
First of all: thank you for your plugin. I find it very useful and use it very often for editing my debug outputs ;-) I use also the compare plugin very often and with this error they can't work together :-(
Now the error:
I debugged the code and could find the reason for this exception:
A NULL pointer access in main() - beNotified(const SCNotification *notify)
so, with:
"
	if (notify == NULL || notify->text == NULL)
		return;
"
at the beginning of the function and everything went OK

**Comment by dail8859** [comment]
I've known it doesn't "play nice" with the Compare plugin but personally I've never seen a crash. Could you please provide:

1. Your Notepad++ debug info (located under the `? > Debug Info` menu)
2. Your ElasticTabstops version (located under `Plugins > Elastic Tabstops > About`)
3. Your Compare plugin version.
4. A set of steps to reproduce the issue.

That if statement is a little too broad (there are several cases where `notify->text` is allowed to be `NULL`) so I would like to track down an exact cause. Thanks.

**Comment by qatanani** [comment]
Hallo and sorry for the delay,

 

it's not a crash, but some data loss bug which deletes some charachters and adds returns to the right file.

I can't reproduce it anymore with the new versions of compare nad elastic.

 

Thanks
 

Mit freundlichen Grüßen
--
Ihsan Qatanani
Alfred-Messel-Weg 40
64287 Darmstadt

Email: qatanani@gmx.de
Mobile: 0176-61833546

 
 

Gesendet: Freitag, 03. März 2017 um 14:35 Uhr
Von: dail8859 <notifications@github.com>
An: dail8859/ElasticTabstops <ElasticTabstops@noreply.github.com>
Cc: qatanani <qatanani@gmx.de>, Author <author@noreply.github.com>
Betreff: Re: [dail8859/ElasticTabstops] Exception and data corruption on using with compare plugin (#5)


I've know it doesn't "play nice" with the Compare plugin but personally I've never seen a crash. Could you please provide:


	Your Notepad++ debug info (located under the ? > Debug Info menu)
	Your ElasticTabstops version (located under Plugins > Elastic Tabstops > About)
	Your Compare plugin version.
	A set of steps to reproduce the issue.


That if statement is a little too broad (there are several cases where notify->text is allowed to be NULL) so I would like to track down an exact cause. Thanks.

**Comment by dail8859** [comment]
No problem. If you do encounter this issue again and are able to reproduce it, feel free to reopen this issue as I would be glad to look into it more.
